# Generated by Django 5.0.7 on 2024-10-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20, null=True)),
                ('psw', models.CharField(max_length=10, null=True)),
                ('repeatpassword', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
